import React, { useEffect, useState } from 'react';
import {
  View,
  StyleSheet,
  Dimensions,
  Image,
  ActivityIndicator,
} from 'react-native';
import { useRouter } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { BaseText as Text } from '@/components/ui/Base';
import Colors from '@/constants/Colors';
import apiService from '@/lib/services/ApiService';
import { useAuth } from '@/lib/context/AuthContext';

const { width: screenWidth } = Dimensions.get('window');

// Polling interval in milliseconds
const POLL_INTERVAL = 3000;
// Maximum polling duration in milliseconds (2 minutes)
const MAX_POLL_DURATION = 120000;

export default function GeneratingSoulProfileScreen() {
  const router = useRouter();
  const { backendUser, refreshUserData } = useAuth();
  const [isPolling, setIsPolling] = useState(true);

  useEffect(() => {
    let pollTimer: NodeJS.Timeout;
    let timeoutTimer: NodeJS.Timeout;
    const startTime = Date.now();

    // Store the initial timestamp to detect changes
    const initialTimestamp = backendUser?.last_soul_profile_generated_at || null;
    console.log('[GeneratingSoulProfile] Initial timestamp:', initialTimestamp);

    const checkSoulProfile = async () => {
      try {
        // Refresh user data to check if soul profile was generated
        await refreshUserData();

        // Check if profile was generated by checking last_soul_profile_generated_at
        // We need to refetch to get the latest data
        const response = await apiService.getCurrentUser();

        if (response.success && response.data) {
          const lastGenerated = response.data.last_soul_profile_generated_at;

          // Check if timestamp changed (new profile generated) OR if this is first profile
          const hasNewProfile = initialTimestamp === null
            ? lastGenerated !== null
            : lastGenerated !== initialTimestamp;

          if (hasNewProfile) {
            console.log('[GeneratingSoulProfile] New profile detected, navigating to matches');
            setIsPolling(false);
            // Navigate to top expert matches screen
            router.replace('/top-expert-matches');
            return;
          }
        }

        // Check if we've exceeded max poll duration
        if (Date.now() - startTime >= MAX_POLL_DURATION) {
          console.log('[GeneratingSoulProfile] Max polling duration reached, navigating anyway');
          setIsPolling(false);
          router.replace('/top-expert-matches');
          return;
        }

        // Continue polling
        pollTimer = setTimeout(checkSoulProfile, POLL_INTERVAL);
      } catch (error) {
        console.error('[GeneratingSoulProfile] Error checking soul profile:', error);
        // Continue polling even on error
        pollTimer = setTimeout(checkSoulProfile, POLL_INTERVAL);
      }
    };

    // Start polling
    checkSoulProfile();

    // Safety timeout - navigate after max duration regardless
    timeoutTimer = setTimeout(() => {
      setIsPolling(false);
      router.replace('/top-expert-matches');
    }, MAX_POLL_DURATION);

    return () => {
      if (pollTimer) clearTimeout(pollTimer);
      if (timeoutTimer) clearTimeout(timeoutTimer);
    };
  }, []);

  const handleBack = () => {
    router.back();
  };

  return (
    <SafeAreaView style={styles.container}>
      {/* Back Button */}
      <View style={styles.header}>
        <Ionicons
          name="arrow-back"
          size={24}
          color={Colors.textSecondary}
          onPress={handleBack}
          style={styles.backButton}
        />
      </View>

      {/* Content */}
      <View style={styles.content}>
        {/* TODO: Add your custom illustration/animation asset here */}
        {/* The design shows two cute characters - a blue ghost and a pink creature */}
        {/* Replace this placeholder with: */}
        <Image source={require('@/assets/images/soul-matches.png')} style={styles.illustration} />

        {/* Text */}
        <View style={styles.textContainer}>
          <Text style={styles.mainText}>
            Generating <Text style={styles.highlightText}>Soul Profile</Text>
          </Text>
          <Text style={styles.mainText}>and finding</Text>
          <Text style={styles.highlightText}>Soul Matches...</Text>
        </View>
      </View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  header: {
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  backButton: {
    padding: 8,
  },
  content: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 40,
  },
  illustration: {
    width: 100,
    height: 100,
    resizeMode: 'contain',
    marginBottom: 20,
  },
  textContainer: {
    alignItems: 'center',
  },
  mainText: {
    fontSize: 20,
    color: '#1F2937',
    textAlign: 'center',
    lineHeight: 32,
  },
  highlightText: {
    fontSize: 20,
    color: Colors.primary,
    textAlign: 'center',
    lineHeight: 32,
  },
});
